import {styled} from 'stitches.config'
import Box from '@/design-system/primitives/Box'
import Button from '@/design-system/primitives/Button'
import Head from 'next/head'
import { ReactNode} from 'react'
import Search from '@/design-system/Search'
import Settings from '@/design-system/Settings'
import {useRouter} from 'next/router'
import {useRecoilState} from 'recoil'
import { minWidthTile, maxWidthTile} from 'contexts/cardSettings'
import Auth from '@/design-system/Auth'
import Sidebar from  '@/design-system/Sidebar'

const StyledMain = styled('main', {
    height: '100%',
    boxSizing: 'border-box',
    overflowY: 'hidden',
    minHeight: '88vh',
    alignItems:'flex-start',
    justifyContent:'flex-start',
    overflowX: 'hidden',
    padding: '$0 $4',
    display: 'flex',
    flex: '1',
    flexDirection: 'column',
})

const StyledFooter = styled('footer', {
    padding: '$1 $2',
    backgroundColor: '$background',
    borderRadius: '0',
    fontSize:'$6',
    color:'gray',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
})

const StyledHeader = styled('header', {
    position: 'sticky',
    top:'0',
    zIndex:'10',
    backgroundColor: '$background',
    padding: '$2 $4',
    height:'$4',
    overflow:'hidden',
    color: '$text',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // borderBottom:'1px solid lightgray'
})

type Props = {
    children?: ReactNode;
    isSelected:boolean;
}



const Layout = ({children, isSelected}:Props) =>{
    const router = useRouter()
    const [maxWidth, setMaxWidth] = useRecoilState(maxWidthTile)
    const [minWidth, setMinWidth] = useRecoilState(minWidthTile)

    return(
        <Box layout='flexBoxRow' css={{width:'100%',gap:'0', overflow:'hidden'}}>
            <Head>
                <title>Boardroom Governance</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box css={{height:'100%',
                justifyContent:'space-between',
                position:'relative',
                width:'100%', overflow:'scroll', maxHeight:'100vh', boxSizing:'border-box'}}>
                
                <StyledHeader>
        
                        <Box layout='flexBoxRow' css={{gap:'$1', alignItems:'center'}}>
                            <Auth />
                            <Box as={'span'} css={{ color: 'lightgray', userSelect:'none' }}>|</Box>
                            {!isSelected && (
                                <Settings
                                setMaxWidth={setMaxWidth}
                                setMinWidth={setMinWidth}
                                maxWidth={maxWidth}
                                minWidth={minWidth}
                                />
                            )}
                            
                            {isSelected && (
                                <>
                                    <Button
                                        onClick={() => router.push('/')}
                                        css={{ padding: '$0 $1', 
                                        color:'gray',
                                        display:'inline-block', borderRadius:'$round',
                                        '&:hover':{
                                            border:'1px solid $black',
                                            color:'$black'
                                        }
                                        }}
                                        look={"outlined"}>
                                        <svg width="15" 
                                        style={{ position: 'relative', top: '1px' }}
                                        height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6.85355 3.14645C7.04882 3.34171 7.04882 3.65829 6.85355 3.85355L3.70711 7H12.5C12.7761 7 13 7.22386 13 7.5C13 7.77614 12.7761 8 12.5 8H3.70711L6.85355 11.1464C7.04882 11.3417 7.04882 11.6583 6.85355 11.8536C6.65829 12.0488 6.34171 12.0488 6.14645 11.8536L2.14645 7.85355C1.95118 7.65829 1.95118 7.34171 2.14645 7.14645L6.14645 3.14645C6.34171 2.95118 6.65829 2.95118 6.85355 3.14645Z" fill="currentColor" fillRule="evenodd" clipRule="evenodd"></path></svg>
                                    </Button>
                                </>
                            )}
                        </Box>
                        
                        <Box as='p' css={{color:'gray',userSelect:'none', marginLeft:'$1', textTransform:'uppercase'}}>Boardroom Governance</Box>
    
                    <Search />
                   
                      
                
                </StyledHeader>
                <StyledMain>
                    {children}
                </StyledMain>
                <StyledFooter>
                    <span style={{fontSize:'inherit'}}>BoardRoom Governance</span>
                    <span style={{ fontSize: 'inherit' }}>2021</span>
                </StyledFooter>
            </Box>
            <Sidebar/>
        </Box>
    )
}

export default Layout